name: 🔨 Build Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build .
        working-directory: v2/cmd/nuclei/

      - name: Test
        run: go test ./...
        working-directory: v2/

      - name: Integration Tests
        env:
          GH_ACTION: true
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          chmod +x run.sh
          bash run.sh ${{ matrix.os }}
        working-directory: integration_tests/

      - name: Race Condition Tests
        if: ${{ matrix.os != 'windows-latest' }} # known issue: https://github.com/golang/go/issues/46099
        run: go run -race . -u scanme.sh
        working-directory: v2/cmd/nuclei/